TYPO3:
  Form:
    Presets:
      Default:
        ########### DEFAULT###########
        formElementTypes:

          # NAMING: base class for everything is RENDERABLE
          'TYPO3.Form:Base':
            renderingOptions:
              templatePathPattern: 'resource://{@package}/Private/Form/{@type}.html'
              layoutPathPattern: 'resource://{@package}/Private/Form/Layout/{@type}.html'

          'TYPO3.Form:Form':
            superTypes: ['TYPO3.Form:Base']
            rendererClassName: 'TYPO3\Form\Domain\Renderer\FluidFormRenderer'
            renderingOptions:
              renderableNameInTemplate: 'form'

          'TYPO3.Form:Page':
            superTypes: ['TYPO3.Form:Base']
            implementationClassName: 'TYPO3\Form\Domain\Model\Page'
            renderingOptions:
              renderableNameInTemplate: 'page'

          'TYPO3.Form:FormElement':
            superTypes: ['TYPO3.Form:Base']
            implementationClassName: 'TYPO3\Form\Domain\Model\GenericFormElement'
            renderingOptions:
              renderableNameInTemplate: 'element'

          'TYPO3.Form:Section':
            superTypes: ['TYPO3.Form:FormElement']
            implementationClassName: 'TYPO3\Form\Domain\Model\Section'
            renderingOptions:
              renderableNameInTemplate: 'section'

          'TYPO3.Form:Textfield':
            superTypes: ['TYPO3.Form:FormElement']
          'TYPO3.Form:Select':
            superTypes: ['TYPO3.Form:FormElement']
          'TYPO3.Form:Date':
            superTypes: ['TYPO3.Form:FormElement']
          'TYPO3.Form:Checkboxes':
            superTypes: ['TYPO3.Form:FormElement']
          'TYPO3.Form:Radiobuttons':
            superTypes: ['TYPO3.Form:FormElement']
#            processingRule:
#              mapping:
#                availableOptions:
#                  dateFormat:
##                    type: string // boolean // .... # for graphical UI
##                    label: '....' # for graphical UI
#                    converterOptionName: 'TYPO3\FLOW3\Property\TypeConverter\DateTimeConverter::format'
#                targetType: '\DateTime'
#                options:
#                  dateFormat: 'Y-m-d'
        finisherTypes:
          'TYPO3.Form:Redirect':
            implementationClassName: 'TYPO3\Form\Domain\Model\Finisher\RedirectFinisher'
            availableOptions:
              sender:
                type: 'string'

    ############ CUSTOM PRESET #############
      facebook:
        parentPreset: 'Default'
        formElementTypes:
          'TYPO3.Form:Base':
            implementationClassName: 'SomethingElse'