TYPO3:
  Form:
    #yamlPersistenceManager:
      #allowedDirectories:
        # list of allowed directories
    supertypeResolver:
      hiddenProperties: []
    presets:
      default:
        title: 'Default'

        ########### Required CSS / JavaScripts ###########

        stylesheets: []
        javaScripts: []

        ########### DEFAULT FORM ELEMENT DEFINITIONS ###########
        formElementTypes:

          ### BASE ELEMENTS ###

          # NAMING: base class for everything is RENDERABLE
          'TYPO3.Form:Base':
            renderingOptions:
              templatePathPattern: 'resource://{@package}/Private/Form/{@type}.html'
              partialPathPattern: 'resource://{@package}/Private/Form/Partials/{@type}.html'
              layoutPathPattern: 'resource://{@package}/Private/Form/Layout/{@type}.html'

          'TYPO3.Form:Form':
            superTypes: ['TYPO3.Form:Base']
            rendererClassName: 'TYPO3\Form\Core\Renderer\FluidFormRenderer'
            renderingOptions:
              renderableNameInTemplate: 'form'

          'TYPO3.Form:FormElement':
            superTypes: ['TYPO3.Form:Base']
            implementationClassName: 'TYPO3\Form\FormElements\GenericFormElement'
            renderingOptions:
              renderableNameInTemplate: 'element'

          ### FORM ELEMENTS: CONTAINER ###
          'TYPO3.Form:Page':
            superTypes: ['TYPO3.Form:Base']
            implementationClassName: 'TYPO3\Form\Core\Model\Page'
            renderingOptions:
              renderableNameInTemplate: 'page'

          'TYPO3.Form:PreviewPage':
            superTypes: ['TYPO3.Form:Page']

          'TYPO3.Form:Section':
            superTypes: ['TYPO3.Form:FormElement']
            implementationClassName: 'TYPO3\Form\FormElements\Section'
            renderingOptions:
              renderableNameInTemplate: 'section'


          ### FORM ELEMENTS: INPUT ###
          'TYPO3.Form:TextMixin': []

          'TYPO3.Form:SingleLineText':
            superTypes: ['TYPO3.Form:FormElement', 'TYPO3.Form:TextMixin']
          'TYPO3.Form:MultiLineText':
            superTypes: ['TYPO3.Form:FormElement', 'TYPO3.Form:TextMixin']

          ### FORM ELEMENTS: SELECT ###
          'TYPO3.Form:SelectionMixin': []
          'TYPO3.Form:SingleSelectionMixin':
            superTypes: ['TYPO3.Form:SelectionMixin']
          'TYPO3.Form:MultiSelectionMixin':
            superTypes: ['TYPO3.Form:SelectionMixin']

          'TYPO3.Form:Checkbox':
            superTypes: ['TYPO3.Form:FormElement']
            properties:
              value: 1
          'TYPO3.Form:MultipleSelectCheckboxes':
            superTypes: ['TYPO3.Form:FormElement', 'TYPO3.Form:MultiSelectionMixin']
          'TYPO3.Form:MultipleSelectDropdown':
            superTypes: ['TYPO3.Form:FormElement', 'TYPO3.Form:MultiSelectionMixin']
          'TYPO3.Form:SingleSelectRadiobuttons':
            superTypes: ['TYPO3.Form:FormElement', 'TYPO3.Form:SingleSelectionMixin']
          'TYPO3.Form:SingleSelectDropdown':
            superTypes: ['TYPO3.Form:FormElement', 'TYPO3.Form:SingleSelectionMixin']

          ### FORM ELEMENTS: CUSTOM ###
          'TYPO3.Form:DatePicker':
            superTypes: ['TYPO3.Form:FormElement']
            implementationClassName: 'TYPO3\Form\FormElements\DatePicker'
            properties:
              dateFormat: 'Y-m-d'
              enableDatePicker: true
              displayTimeSelector: false
          'TYPO3.Form:FileUpload':
            superTypes: ['TYPO3.Form:FormElement']
            implementationClassName: 'TYPO3\Form\FormElements\FileUpload'
            properties:
              allowedExtensions: ['pdf', 'doc']
          'TYPO3.Form:ImageUpload':
            superTypes: ['TYPO3.Form:FormElement']
            implementationClassName: 'TYPO3\Form\FormElements\ImageUpload'
            properties:
              allowedTypes: ['jpeg', 'png', 'bmp']



           ### FINISHERS ###
        finisherTypes:
          'TYPO3.Form:Redirect':
            implementationClassName: 'TYPO3\Form\Finishers\RedirectFinisher'
            availableOptions:
              sender:
                type: 'string'

        ########### CUSTOM PRESETS ###########
#      somePresetName:
#        parentPreset: 'Default'
#        title: 'Some Preset'
#        stylesheets:
#          css1:
#            source: 'resource://SomePackage/Public/Css/File1.css'
#        javaScripts:
#          js1:
#            source: 'resource://SomePackage/Public/JavaScript/File1.js'
#            skipInFormBuilder: true
#        formElementTypes:
#          'TYPO3.Form:Base':
#            renderingOptions:
#              templatePathPattern: 'resource://TYPO3.SomePackage/Private/Form/{@type}.html'